server:
  port: 8080
spring:
  webflux:
    base-path: /webflux-ratelimit
resilience4j.ratelimiter:
  instances:
    rate-limit-1:
      limitForPeriod: 10
      limitRefreshPeriod: 500ms
      timeoutDuration: 0
    rate-limit-2:
      limitForPeriod: 10
      limitRefreshPeriod: 500ms
      timeoutDuration: 0
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: /
      path-mapping:
        prometheus: /prometheus
        health: /health
  server:
    port: 18443
